[package]
name = "game_off_2022"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
bevy_ecs = "0.8.1"
macroquad = "0.3.24"

[build-dependencies]
winres = "0.1"
